import type { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "lead-operations",
    id: "PROJECT / 001",
    title: "Lead intelligence",
    summary: "A lead management and performance optimization platform connecting lead flow, demand configuration, acquisition metrics, and AI-assisted insight.",
    role: "Lead Software engineer",
    period: "Apr 2026 - present",
    system: "Lead management and performance platform",
    systems: ["Next.js", "TypeScript", "AWS", "PostgreSQL", "DynamoDB", "Redis", "Snowflake", "OpenSearch"],
    challenge: "Bring lead sources, campaign performance, demand settings, and acquisition outcomes into one place so teams can understand what is working, where budget is best spent, and which areas need attention.",
    challengeTitle: "Turn acquisition data into clear action.",
    built: "A unified platform for following lead flow and performance across sources and segments, with detailed reporting, drill-down analysis, CPA and conversion outcomes, AI-assisted summaries, and an operational admin layer for the configuration behind the wider system.",
    builtTitle: "One view from source to outcome.",
    decisions: [
      "Structured reporting around lead source, segment, CPA, and conversion outcomes so teams can move from a headline metric to the underlying performance drivers.",
      "Kept demand settings, lead distribution, and scoring close to the reporting surface so administrators can investigate results in context.",
      "Used AI-assisted insights to surface trends and summarize performance while leaving decisions and configuration under human control.",
      "Made the admin panel the operational layer for maintaining the rules and settings that drive the wider lead system.",
    ],
    decisionsTitle: "Performance and operations, connected.",
    noteLabel: "Disclosure",
    note: "The client and implementation details are intentionally withheld. This record describes only the product shape and engineering responsibilities that can be discussed publicly.",
    links: [],
  },
  {
    slug: "recruiting-flows",
    id: "PROJECT / 002",
    title: "Recruiting flows",
    summary: "A recruiting automation SaaS connecting sourcing, multi-channel journeys, scheduling, and AI voice interviews.",
    role: "Software engineer",
    period: "Sep 2026 - present",
    system: "Recruiting automation SaaS",
    systems: ["Next.js", "TypeScript", "PostgreSQL", "AWS", "React Flow", "Telnyx", "Cognito"],
    challenge: "Coordinate long-running candidate journeys across email, SMS, voice, replies, appointments, timeouts, and human decisions without losing state or auditability.",
    challengeTitle: "Turn a graph into a reliable journey.",
    built: "A product that carries a lead from targeted lists through visual automation flows to booked appointments, alongside AI voice-screening scenarios, invitations, recordings, and scored results.",
    builtTitle: "Recruiting and interviews in one system.",
    decisions: [
      "Modelled every run with an explicit lifecycle so waiting, conversation, human review, sleep, and completion remain unambiguous.",
      "Routed deterministic events before AI interpretation and kept domain-specific behavior outside the reusable flow engine.",
      "Used one auditable event path for replies, appointments, timers, tool calls, decisions, and run endings.",
      "Designed safety rails to defer work rather than silently drop it when quiet hours, daily limits, or provider constraints apply.",
    ],
    decisionsTitle: "Facts first; every transition recorded.",
    noteLabel: "Disclosure",
    note: "The client name and confidential product details are omitted. The case study is limited to the supplied high-level architecture and product behavior.",
    links: [],
  },
  {
    slug: "connected-insole-platform",
    id: "PROJECT / 003",
    title: "Connected insole",
    summary: "A multilingual public web platform for a privacy-first smart insole across Identity and wellbeing audiences.",
    role: "Lead Software engineer",
    period: "Aug 2026 - present",
    system: "Three-site content platform",
    systems: ["Next.js", "Content management", "i18n", "Accessibility", "Self-hosting", "Enquiry capture"],
    challenge: "Explain one unfamiliar product clearly to different audiences while preserving careful wellbeing language, privacy claims, and a consistent identity across three connected sites.",
    challengeTitle: "One signal, several audiences.",
    built: "A 22-page platform connecting a central product site with dedicated wellbeing and Identity experiences, delivered in English, French, and Spanish for 66 page-locale combinations.",
    builtTitle: "Three sites, one governed publishing system.",
    decisions: [
      "Made every page editable by non-developers through a built-in content system.",
      "Kept content, media, and enquiries on infrastructure controlled by the company rather than a third-party site builder.",
      "Treated accessibility, privacy, terms, and enquiry capture as part of the core delivery rather than add-ons.",
      "Separated Identity and wellbeing narratives while keeping the product language and visual system coherent.",
    ],
    decisionsTitle: "Governance belongs in the product.",
    noteLabel: "Scope note",
    note: "Public descriptions use wellness language only and make no medical claims. No product performance measurements or confidential partner information are included.",
    links: [],
  },
  {
    slug: "video-ingestion-platform",
    id: "PROJECT / 004",
    title: "Video ingestion platform",
    summary: "A cloud-based platform for ingesting and monitoring live camera streams, supporting fall and neglect detection through automated event processing.",
    role: "Software engineer",
    period: "Mar - Apr 2026",
    system: "Cloud video ingestion and monitoring platform",
    systems: ["Python", "TypeScript", "Deno", "Supabase", "PostgreSQL", "Docker", "Docker Compose", "FFmpeg", "SRS", "Nginx", "DigitalOcean", "Ubuntu", "Bash", "cloud-init"],
    challenge: "Build dependable cloud infrastructure and an ingestion path capable of receiving, processing, and monitoring live camera streams while connecting cleanly with the wider backend.",
    challengeTitle: "Keep live video moving reliably.",
    built: "Infrastructure and ingestion services for provisioning and deploying DigitalOcean servers, containerizing the platform, processing RTMP streams, and integrating stream workflows with Supabase-backed services.",
    builtTitle: "From camera stream to backend event.",
    decisions: [
      "Automated server provisioning with cloud-init and Bash so new Ubuntu hosts could be prepared consistently.",
      "Containerized the ingestion stack with Docker and Docker Compose to keep deployment and service boundaries repeatable.",
      "Combined SRS, FFmpeg, and Nginx to receive, process, and route RTMP streams through the platform.",
      "Connected the ingestion pipeline with Supabase and PostgreSQL services so stream state and downstream event workflows remained coordinated.",
    ],
    decisionsTitle: "Repeatable infrastructure for continuous streams.",
    noteLabel: "Disclosure",
    note: "The product name, client details, and confidential detection logic are intentionally omitted. This record covers only the infrastructure and ingestion responsibilities that can be discussed publicly.",
    links: [],
  },
  {
    slug: "digital-health-platform",
    id: "PROJECT / 005",
    title: "Digital health platform",
    summary: "A digital health platform for tracking medical data, therapies, medications, blood-test results, and biochemical risk factors while helping patients and healthcare professionals monitor trends and communicate.",
    role: "Chief Information Officer",
    period: "Jan 2025 - Jun 2026",
    system: "Cross-platform digital health platform",
    systems: ["Flutter", "Dart", "Firebase", "Firestore", "Firebase Authentication", "Cloud Functions", "Firebase Cloud Messaging", "Node.js", "TypeScript", "Google Cloud", "Stream Chat", "Stream Video", "BLoC", "GoRouter", "GitHub Actions", "CI/CD", "Athena"],
    challenge: "Connect health data, therapies, medications, risk calculations, communication, and healthcare integrations into a reliable experience for both patients and healthcare professionals.",
    challengeTitle: "Turn health data into a shared care picture.",
    built: "A cross-platform health product spanning the mobile application, backend services, data-processing workflows, health-risk calculations, doctor–patient communication, notifications, subscriptions, medical-document handling, and third-party healthcare integrations.",
    builtTitle: "One connected workflow for ongoing care.",
    decisions: [
      "Kept health data, therapies, medications, blood-test results, and risk factors connected so users could follow trends over time.",
      "Built communication, notifications, and video capabilities into the same product journey for more direct doctor–patient coordination.",
      "Used Firebase, Cloud Functions, and Google Cloud services to support authentication, processing workflows, messaging, and reliable notifications.",
      "Handled medical documents, subscriptions, and healthcare integrations as governed parts of the product rather than separate utilities.",
    ],
    decisionsTitle: "Care data, communication, and infrastructure together.",
    noteLabel: "Disclosure",
    note: "The product names, patient information, clinical details, and proprietary health-risk methodology are intentionally omitted. This record describes only the product scope and engineering responsibilities that can be discussed publicly.",
    links: [],
  },
  {
    slug: "sports-community-platform",
    id: "PROJECT / 006",
    title: "Sports community platform",
    summary: "A global sports product combining real-time mobile and web experiences with interactive maps, messaging, onboarding, referrals, and engagement analytics.",
    role: "Lead software engineer",
    period: "Jun 2024 - Feb 2026",
    system: "Cross-platform consumer product",
    systems: ["Flutter", "Angular", "FastAPI", "Node.js", "Go", "PHP", "Firebase", "PostgreSQL"],
    challenge: "Grow an active sports community while keeping onboarding, real-time activity, maps, messaging, and the wider product journey consistent across mobile and web.",
    challengeTitle: "Make a growing sports community feel immediate.",
    built: "A connected product experience where users can move smoothly through onboarding and referral journeys, interact through live features and messaging, and explore map-based content, while product teams can understand engagement through analytics dashboards and event tracking.",
    builtTitle: "One sports experience across every touchpoint.",
    decisions: [
      "Kept the core journey consistent between mobile and web so users did not lose context when moving between platforms.",
      "Made live activity and messaging dependable enough to support an experience built around timely interaction.",
      "Improved onboarding and referral journeys as the audience grew, reducing friction before users reached the product's core value.",
      "Connected interactive maps with engagement reporting so both users and product teams had clearer visibility into activity.",
    ],
    decisionsTitle: "Growth without a fragmented experience.",
    noteLabel: "Verified outcomes",
    note: "The supplied CV records a 12x increase in active users over 16 months and a 22% increase in session duration after product and analytics improvements. The product name is intentionally omitted.",
    links: [],
  },
  {
    slug: "regulatory-compliance-platform",
    id: "PROJECT / 007",
    title: "Regulatory compliance platform",
    summary: "An enterprise compliance and risk product that helps teams follow regulatory change, organize evidence, and act on country-specific requirements.",
    role: "Sole software engineer",
    period: "Jan 2024 - Mar 2026",
    system: "Enterprise compliance platform",
    systems: ["Node.js", "GraphQL", "React", "AWS", "MongoDB", "Redis", "Auth0", "OpenAI"],
    challenge: "Turn a continuous stream of regulatory updates into a structured workflow that enterprise teams can review, understand, document, and follow over time.",
    challengeTitle: "Make regulatory change manageable.",
    built: "A compliance workspace that brings regulatory monitoring, country-specific updates, document handling, risk information, and timely browser and WhatsApp notifications into one product, with AI-assisted research for finding and summarizing relevant developments.",
    builtTitle: "From regulatory signal to documented action.",
    decisions: [
      "Organized regulatory information around the countries and topics users needed to monitor rather than presenting an undifferentiated news feed.",
      "Connected structured compliance data with supporting documents so teams could keep context and evidence together.",
      "Used browser and WhatsApp notifications to bring important changes to users instead of relying on repeated manual checks.",
      "Added AI-assisted research as a way to navigate new developments while keeping the underlying sources available for review.",
    ],
    decisionsTitle: "A clearer path through regulatory change.",
    noteLabel: "Scope note",
    note: "This record focuses on the product experience and publicly discussable responsibilities without exposing the product name, customer details, or regulated business information.",
    links: [],
  },
  {
    slug: "performance-reporting",
    id: "PROJECT / 008",
    title: "Performance reporting",
    summary: "A custom frontend workflow for generating custom fitness performance reports and working with the resulting PDF through a purpose-built drag-and-drop experience.",
    role: "Frontend engineer",
    period: "Feb - May 2023",
    system: "Custom PDF reporting workflow",
    systems: ["Frontend engineering", "PDF generation", "Drag and drop", "Report customization"],
    challenge: "Give users control over a highly customized report while keeping the path from configuration to generated PDF understandable and direct.",
    challengeTitle: "Make a generated report feel editable.",
    built: "A frontend reporting experience that supports custom PDF generation and a custom drag-and-drop interaction for working with the document after it has been produced.",
    builtTitle: "A report workflow beyond the export button.",
    decisions: [
      "Kept report customization visible before generation so users could understand the output they were creating.",
      "Made PDF generation a clear transition from configuration into a finished document rather than a detached download action.",
      "Built a custom drag-and-drop experience around the generated result so post-generation work stayed inside the same flow.",
    ],
    decisionsTitle: "Keep control on both sides of generation.",
    noteLabel: "Disclosure",
    note: "The client name, report contents, and proprietary performance methodology are intentionally omitted.",
    links: [],
  },
  {
    slug: "bachelors-thesis-app",
    id: "PROJECT / 009",
    title: "My bachelor’s thesis app",
    summary: "An Android fitness and social application, documented as a technical case study.",
    role: "Android developer",
    period: "Jun - Aug 2023",
    system: "Native Android application",
    systems: ["Kotlin", "Jetpack Compose", "MVVM", "Clean Architecture", "Hilt", "Room", "Retrofit", "Firebase"],
    challenge: "Design an Android application that brings fitness activity and social interaction into one coherent product structure.",
    challengeTitle: "Keep social fitness coherent.",
    built: "A native Android application using a declarative interface, layered architecture, local persistence, remote data access, dependency injection, and Firebase services.",
    builtTitle: "A layered native system.",
    decisions: [
      "Compose keeps interface state explicit and components reusable.",
      "MVVM and Clean Architecture separate product behavior from platform details.",
      "Room supports local persistence while Retrofit handles remote data access.",
    ],
    decisionsTitle: "Architecture as a maintenance tool.",
    noteLabel: "Scope note",
    note: "The public case study intentionally avoids unverified usage numbers and confidential implementation details.",
    links: [],
  },
];
